spring:
  application:
    name: spring-async
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 3
      max-total: 20
      max-idle: 20
      min-idle: 1
      max-wait-millis: 60000
---
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations:
    - classpath*: com/example/springasync/**/mapper/**/*Mapper.xml